apiVersion: v1
kind: ReplicationController
metadata:
  name: guestbook-app
  labels:
    name: frontend
    heritage: helm
spec:
  replicas: 2
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
